services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mongo
    env_file: .env

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: